name: DevOps CI Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Display Welcome Message
        run: echo "🚀 DevOps CI/CD Pipeline Started"

      - name: Show Current Date
        run: date

      - name: List Files
        run: ls -la

      - name: Success Message
        run: echo "✅ Workflow executed successfully!"           